# Generated by Django 3.1.1 on 2020-09-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200921_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Eng: Mounaf Alahmad', max_length=30),
        ),
    ]
