# Generated by Django 3.1.1 on 2020-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.CharField(default='60,000', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='40 H', max_length=5),
        ),
    ]
