# Generated by Django 3.1.1 on 2020-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200921_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.CharField(default='60,000 SP', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='40 Hours', max_length=5),
        ),
    ]
