# Generated by Django 3.1.1 on 2020-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200921_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(default='Redhat', max_length=30),
        ),
    ]
