# Generated by Django 3.1.1 on 2020-09-23 13:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200923_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Training Courses',
            field=models.ManyToManyField(blank=True, related_name='_instructor_Training Courses_+', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequiste',
            field=models.ManyToManyField(blank=True, to='course.Courses'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
