# Generated by Django 3.1.1 on 2020-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200923_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequiste',
            field=models.ManyToManyField(blank=True, to='course.Courses'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Training Courses',
            field=models.ManyToManyField(blank=True, related_name='_instructor_Training Courses_+', to='course.Course'),
        ),
    ]
