# Generated by Django 3.1.1 on 2020-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200923_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Training Courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='material',
            field=models.ManyToManyField(blank=True, related_name='_instructor_material_+', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequiste',
            field=models.ManyToManyField(blank=True, to='course.Courses'),
        ),
    ]
